spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sky-agent?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=GMT+1:00
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000 # 1 day in milliseconds